### PR TITLE
deps: update react-binding-component

### PR DESCRIPTION
**Pull request by jkvim**
@yorkie please review, thank you.

update:
- update react-binding-component to v1.0.4
- bump patch

### CODE REVIEW

**Comment by yorkie** [comment]
BTW, I got the error when installing:

```
npm ERR! peerinvalid The package react@0.14.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-binding-component@1.0.3 wants react@0.14.3
npm ERR! peerinvalid Peer react-dom@0.14.7 wants react@^0.14.7
```

May I ask you to fix this as well?

**Comment by yorkie** [comment]
Merged in b2a652c and bump version v2.7.4, thank you @jkvim

**Comment by jkvim** [comment]
@yorkie when i installed weflex-ui by npm, the package at `node_modules/weflex-ui/lib` lack of `framework.css`, would you mind publishing again?

**Comment by yorkie** [comment]
2.7.5 has been published.

**Pull request merged**
